name: Crawl news

#Run automatically every 24 hours
on:
  schedule:
    - cron: "0 */24 * * *"

  # This command allows to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6' 
          cache: 'pip' # caching pip dependencies
      - run: pip install PyMuPDF requests beautifulsoup4 lxml
      - run: python main.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update README.md"
          git push